"""add project table

Revision ID: 03746b7be990
Revises: 7cec1b047fea
Create Date: 2026-08-31 17:40:49.345882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03746b7be990'
down_revision: Union[str, Sequence[str], None] = '7cec1b047fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='project_status'), nullable=False),
    sa.Column('global_config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('parent_folder_id', sa.Integer(), nullable=True),
    sa.Column('project_folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['file_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_folder_id'], ['file_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_code'), 'projects', ['code'], unique=True)
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_projects_parent_folder_id'), 'projects', ['parent_folder_id'], unique=False)
    op.create_index(op.f('ix_projects_project_folder_id'), 'projects', ['project_folder_id'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.add_column('form_definitions', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_form_definitions_project_id'), 'form_definitions', ['project_id'], unique=False)
    op.create_foreign_key(None, 'form_definitions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'form_definitions', type_='foreignkey')
    op.drop_index(op.f('ix_form_definitions_project_id'), table_name='form_definitions')
    op.drop_column('form_definitions', 'project_id')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_project_folder_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_parent_folder_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_index(op.f('ix_projects_code'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
