"""add project definitions

Revision ID: 1ae705fb502a
Revises: 52bfd5098470
Create Date: 2026-08-22 22:01:54.810358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae705fb502a'
down_revision: Union[str, Sequence[str], None] = '52bfd5098470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='project_status'), nullable=False),
    sa.Column('global_config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_definitions_code'), 'project_definitions', ['code'], unique=True)
    op.create_index(op.f('ix_project_definitions_created_by'), 'project_definitions', ['created_by'], unique=False)
    op.create_index(op.f('ix_project_definitions_status'), 'project_definitions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_definitions_status'), table_name='project_definitions')
    op.drop_index(op.f('ix_project_definitions_created_by'), table_name='project_definitions')
    op.drop_index(op.f('ix_project_definitions_code'), table_name='project_definitions')
    op.drop_table('project_definitions')
    # ### end Alembic commands ###
