"""add project question dependencies

Revision ID: 253a3251d13d
Revises: 4148608a6a00
Create Date: 2026-08-25 18:16:47.341302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253a3251d13d'
down_revision: Union[str, Sequence[str], None] = '4148608a6a00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_question_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_question_id', sa.Integer(), nullable=False),
    sa.Column('source_question_id', sa.Integer(), nullable=False),
    sa.Column('operator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_question_id'], ['project_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_question_id'], ['project_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_question_id', 'source_question_id', name='uq_project_question_dependency_pair')
    )
    op.create_index(op.f('ix_project_question_dependencies_source_question_id'), 'project_question_dependencies', ['source_question_id'], unique=False)
    op.create_index(op.f('ix_project_question_dependencies_target_question_id'), 'project_question_dependencies', ['target_question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_question_dependencies_target_question_id'), table_name='project_question_dependencies')
    op.drop_index(op.f('ix_project_question_dependencies_source_question_id'), table_name='project_question_dependencies')
    op.drop_table('project_question_dependencies')
    # ### end Alembic commands ###
