"""add plugin program

Revision ID: 26b4abcf35d6
Revises: cfaa133fb040
Create Date: 2026-09-18 10:54:38.625544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26b4abcf35d6'
down_revision: Union[str, Sequence[str], None] = 'cfaa133fb040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_programs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('allow_user_use', sa.Boolean(), nullable=False),
    sa.Column('allow_user_customization', sa.Boolean(), nullable=False),
    sa.Column('allow_multiple_projects', sa.Boolean(), nullable=False),
    sa.Column('allow_project_creation', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('project_rules', sa.JSON(), nullable=False),
    sa.Column('resource_bindings', sa.JSON(), nullable=False),
    sa.Column('schedule', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'key', name='uq_plugin_programs_plugin_key')
    )
    op.create_index(op.f('ix_plugin_programs_code'), 'plugin_programs', ['code'], unique=False)
    op.create_index(op.f('ix_plugin_programs_created_by'), 'plugin_programs', ['created_by'], unique=False)
    op.create_index(op.f('ix_plugin_programs_is_active'), 'plugin_programs', ['is_active'], unique=False)
    op.create_index(op.f('ix_plugin_programs_key'), 'plugin_programs', ['key'], unique=False)
    op.create_index(op.f('ix_plugin_programs_owner_user_id'), 'plugin_programs', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_plugin_programs_plugin_id'), 'plugin_programs', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_plugin_programs_scope'), 'plugin_programs', ['scope'], unique=False)
    op.create_index(op.f('ix_plugin_programs_status'), 'plugin_programs', ['status'], unique=False)
    op.add_column('projects', sa.Column('program_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_program_id'), 'projects', ['program_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'plugin_programs', ['program_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_program_id'), table_name='projects')
    op.drop_column('projects', 'program_id')
    op.drop_index(op.f('ix_plugin_programs_status'), table_name='plugin_programs')
    op.drop_index(op.f('ix_plugin_programs_scope'), table_name='plugin_programs')
    op.drop_index(op.f('ix_plugin_programs_plugin_id'), table_name='plugin_programs')
    op.drop_index(op.f('ix_plugin_programs_owner_user_id'), table_name='plugin_programs')
    op.drop_index(op.f('ix_plugin_programs_key'), table_name='plugin_programs')
    op.drop_index(op.f('ix_plugin_programs_is_active'), table_name='plugin_programs')
    op.drop_index(op.f('ix_plugin_programs_created_by'), table_name='plugin_programs')
    op.drop_index(op.f('ix_plugin_programs_code'), table_name='plugin_programs')
    op.drop_table('plugin_programs')
    # ### end Alembic commands ###
