"""update plugin program

Revision ID: 280ec12379e6
Revises: 26b4abcf35d6
Create Date: 2026-09-18 12:08:22.554221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280ec12379e6'
down_revision: Union[str, Sequence[str], None] = '26b4abcf35d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugin_project_templates', sa.Column('program_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_plugin_project_templates_program_id'), 'plugin_project_templates', ['program_id'], unique=False)
    op.create_foreign_key(None, 'plugin_project_templates', 'plugin_programs', ['program_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plugin_project_templates', type_='foreignkey')
    op.drop_index(op.f('ix_plugin_project_templates_program_id'), table_name='plugin_project_templates')
    op.drop_column('plugin_project_templates', 'program_id')
    # ### end Alembic commands ###
