"""add relation between resources

Revision ID: 4ce2c8b906d1
Revises: 9c6aace0bc86
Create Date: 2026-09-12 14:35:34.715179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce2c8b906d1'
down_revision: Union[str, Sequence[str], None] = '9c6aace0bc86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_resource_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_resource_id', sa.Integer(), nullable=False),
    sa.Column('source_field_key', sa.String(length=100), nullable=False),
    sa.Column('target_resource_id', sa.Integer(), nullable=False),
    sa.Column('target_field_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_resource_id'], ['plugin_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_resource_id'], ['plugin_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_resource_id', 'source_field_key', 'target_resource_id', 'target_field_key', name='uq_plugin_resource_relation_fields')
    )
    op.create_index(op.f('ix_plugin_resource_relations_source_resource_id'), 'plugin_resource_relations', ['source_resource_id'], unique=False)
    op.create_index(op.f('ix_plugin_resource_relations_target_resource_id'), 'plugin_resource_relations', ['target_resource_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_resource_relations_target_resource_id'), table_name='plugin_resource_relations')
    op.drop_index(op.f('ix_plugin_resource_relations_source_resource_id'), table_name='plugin_resource_relations')
    op.drop_table('plugin_resource_relations')
    # ### end Alembic commands ###
