"""add project questions

Revision ID: 738e1288be8e
Revises: 6e3080cadaeb
Create Date: 2026-08-23 22:33:53.967548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738e1288be8e'
down_revision: Union[str, Sequence[str], None] = '6e3080cadaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('question_definition_id', sa.Integer(), nullable=False),
    sa.Column('question_version_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_definition_id'], ['question_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['project_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_questions_project_id'), 'project_questions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_questions_question_definition_id'), 'project_questions', ['question_definition_id'], unique=False)
    op.create_index(op.f('ix_project_questions_question_version_id'), 'project_questions', ['question_version_id'], unique=False)
    op.create_index(op.f('ix_project_questions_section_id'), 'project_questions', ['section_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_questions_section_id'), table_name='project_questions')
    op.drop_index(op.f('ix_project_questions_question_version_id'), table_name='project_questions')
    op.drop_index(op.f('ix_project_questions_question_definition_id'), table_name='project_questions')
    op.drop_index(op.f('ix_project_questions_project_id'), table_name='project_questions')
    op.drop_table('project_questions')
    # ### end Alembic commands ###
