"""init

Revision ID: 7cec1b047fea
Revises: 
Create Date: 2026-08-31 14:55:36.975009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cec1b047fea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'SUPERVISOR', 'LEADER', name='user_role'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SUSPENDED', 'DEACTIVATED', name='user_status'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True),
    sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token', sa.String(length=512), nullable=True),
    sa.Column('refresh_token_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('login_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('file_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('FOLDER', 'FILE', name='file_node_type'), nullable=False),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('extension', sa.String(length=50), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['file_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_file_nodes_parent_id'), 'file_nodes', ['parent_id'], unique=False)
    op.create_index(op.f('ix_file_nodes_user_id'), 'file_nodes', ['user_id'], unique=False)
    op.create_table('question_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='question_definition_status'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_definitions_code'), 'question_definitions', ['code'], unique=True)
    op.create_index(op.f('ix_question_definitions_created_by'), 'question_definitions', ['created_by'], unique=False)
    op.create_table('question_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ARCHIVED', name='question_group_status'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_groups_created_by'), 'question_groups', ['created_by'], unique=False)
    op.create_index(op.f('ix_question_groups_status'), 'question_groups', ['status'], unique=False)
    op.create_table('form_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('form_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='form_status'), nullable=False),
    sa.Column('global_config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('form_folder_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['form_folder_id'], ['file_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_definitions_code'), 'form_definitions', ['code'], unique=True)
    op.create_index(op.f('ix_form_definitions_created_by'), 'form_definitions', ['created_by'], unique=False)
    op.create_index(op.f('ix_form_definitions_form_folder_id'), 'form_definitions', ['form_folder_id'], unique=True)
    op.create_index(op.f('ix_form_definitions_status'), 'form_definitions', ['status'], unique=False)
    op.create_table('question_group_members',
    sa.Column('question_group_id', sa.Integer(), nullable=False),
    sa.Column('question_definition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_definition_id'], ['question_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_group_id'], ['question_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_group_id', 'question_definition_id')
    )
    op.create_table('question_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_definition_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('question_type', sa.Enum('TEXT', 'LONG_TEXT', 'EMAIL', 'PHONE', 'URL', 'ADDRESS', 'INTEGER', 'DECIMAL', 'PERCENTAGE', 'CURRENCY', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'DROPDOWN', 'AUTOCOMPLETE', 'RATING', 'LIKERT_SCALE', 'RANKING', 'DATE', 'TIME', 'DATETIME', 'DURATION', 'POINT', 'LINE', 'POLYGON', 'AREA', 'PHOTO', 'VIDEO', 'AUDIO', 'FILE', 'SIGNATURE', 'QR_CODE', 'BARCODE', 'ENTITY_SELECT', 'ENTITY_SEARCH', 'CALCULATION', 'NOTE', 'CONSENT', 'HIDDEN', name='question_type'), nullable=False),
    sa.Column('base_config', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_definition_id'], ['question_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_definition_id', 'version', name='uq_question_version')
    )
    op.create_index(op.f('ix_question_versions_created_by'), 'question_versions', ['created_by'], unique=False)
    op.create_index(op.f('ix_question_versions_question_definition_id'), 'question_versions', ['question_definition_id'], unique=False)
    op.create_table('form_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_sections_form_id'), 'form_sections', ['form_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_version_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_version_id', 'value', name='uq_question_option_value')
    )
    op.create_index(op.f('ix_question_options_question_version_id'), 'question_options', ['question_version_id'], unique=False)
    op.create_table('form_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('question_definition_id', sa.Integer(), nullable=False),
    sa.Column('question_version_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['form_definitions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_definition_id'], ['question_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['question_version_id'], ['question_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['section_id'], ['form_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_questions_form_id'), 'form_questions', ['form_id'], unique=False)
    op.create_index(op.f('ix_form_questions_question_definition_id'), 'form_questions', ['question_definition_id'], unique=False)
    op.create_index(op.f('ix_form_questions_question_version_id'), 'form_questions', ['question_version_id'], unique=False)
    op.create_index(op.f('ix_form_questions_section_id'), 'form_questions', ['section_id'], unique=False)
    op.create_table('form_question_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_question_id', sa.Integer(), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('actions_if_true', sa.JSON(), nullable=False),
    sa.Column('actions_if_false', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_question_id'], ['form_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_question_dependencies_target_question_id'), 'form_question_dependencies', ['target_question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_question_dependencies_target_question_id'), table_name='form_question_dependencies')
    op.drop_table('form_question_dependencies')
    op.drop_index(op.f('ix_form_questions_section_id'), table_name='form_questions')
    op.drop_index(op.f('ix_form_questions_question_version_id'), table_name='form_questions')
    op.drop_index(op.f('ix_form_questions_question_definition_id'), table_name='form_questions')
    op.drop_index(op.f('ix_form_questions_form_id'), table_name='form_questions')
    op.drop_table('form_questions')
    op.drop_index(op.f('ix_question_options_question_version_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_form_sections_form_id'), table_name='form_sections')
    op.drop_table('form_sections')
    op.drop_index(op.f('ix_question_versions_question_definition_id'), table_name='question_versions')
    op.drop_index(op.f('ix_question_versions_created_by'), table_name='question_versions')
    op.drop_table('question_versions')
    op.drop_table('question_group_members')
    op.drop_index(op.f('ix_form_definitions_status'), table_name='form_definitions')
    op.drop_index(op.f('ix_form_definitions_form_folder_id'), table_name='form_definitions')
    op.drop_index(op.f('ix_form_definitions_created_by'), table_name='form_definitions')
    op.drop_index(op.f('ix_form_definitions_code'), table_name='form_definitions')
    op.drop_table('form_definitions')
    op.drop_index(op.f('ix_question_groups_status'), table_name='question_groups')
    op.drop_index(op.f('ix_question_groups_created_by'), table_name='question_groups')
    op.drop_table('question_groups')
    op.drop_index(op.f('ix_question_definitions_created_by'), table_name='question_definitions')
    op.drop_index(op.f('ix_question_definitions_code'), table_name='question_definitions')
    op.drop_table('question_definitions')
    op.drop_index(op.f('ix_file_nodes_user_id'), table_name='file_nodes')
    op.drop_index(op.f('ix_file_nodes_parent_id'), table_name='file_nodes')
    op.drop_table('file_nodes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
