"""add submission data from mobile

Revision ID: 824d96304556
Revises: 6a55afcce981
Create Date: 2026-09-05 16:40:37.973439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824d96304556'
down_revision: Union[str, Sequence[str], None] = '6a55afcce981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_id', sa.String(length=255), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=False),
    sa.Column('form_code', sa.String(length=100), nullable=False),
    sa.Column('form_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('answered_questions', sa.Integer(), nullable=False),
    sa.Column('consent_accepted', sa.Boolean(), nullable=False),
    sa.Column('consent_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at_mobile', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_mobile', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['form_id'], ['form_definitions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_id', name='uq_submission_local_id')
    )
    op.create_index(op.f('ix_submissions_agent_id'), 'submissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_submissions_form_id'), 'submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_submissions_local_id'), 'submissions', ['local_id'], unique=True)
    op.create_index(op.f('ix_submissions_project_id'), 'submissions', ['project_id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_table('submission_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('question_code', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'question_id', name='uq_submission_answer_question')
    )
    op.create_index(op.f('ix_submission_answers_question_code'), 'submission_answers', ['question_code'], unique=False)
    op.create_index(op.f('ix_submission_answers_question_id'), 'submission_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_submission_answers_submission_id'), 'submission_answers', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submission_answers_submission_id'), table_name='submission_answers')
    op.drop_index(op.f('ix_submission_answers_question_id'), table_name='submission_answers')
    op.drop_index(op.f('ix_submission_answers_question_code'), table_name='submission_answers')
    op.drop_table('submission_answers')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_project_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_local_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_form_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_agent_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###
