"""add assignment table

Revision ID: 8680557bff66
Revises: e9c7d588ddea
Create Date: 2026-09-03 06:06:26.096242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8680557bff66'
down_revision: Union[str, Sequence[str], None] = 'e9c7d588ddea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_agent_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'agent_id', name='uq_project_agent_assignment')
    )
    op.create_index(op.f('ix_project_agent_assignments_agent_id'), 'project_agent_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_project_agent_assignments_project_id'), 'project_agent_assignments', ['project_id'], unique=False)
    op.create_table('project_agent_assignment_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('file_node_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['project_agent_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_node_id'], ['file_nodes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', 'file_node_id', name='uq_assignment_zone')
    )
    op.create_index(op.f('ix_project_agent_assignment_zones_assignment_id'), 'project_agent_assignment_zones', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_project_agent_assignment_zones_file_node_id'), 'project_agent_assignment_zones', ['file_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_agent_assignment_zones_file_node_id'), table_name='project_agent_assignment_zones')
    op.drop_index(op.f('ix_project_agent_assignment_zones_assignment_id'), table_name='project_agent_assignment_zones')
    op.drop_table('project_agent_assignment_zones')
    op.drop_index(op.f('ix_project_agent_assignments_project_id'), table_name='project_agent_assignments')
    op.drop_index(op.f('ix_project_agent_assignments_agent_id'), table_name='project_agent_assignments')
    op.drop_table('project_agent_assignments')
    # ### end Alembic commands ###
