"""add folder_id_on_project_table

Revision ID: 9bf42a34511c
Revises: d71901c30ddd
Create Date: 2026-08-29 16:24:56.611972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bf42a34511c'
down_revision: Union[str, Sequence[str], None] = 'd71901c30ddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_definitions', sa.Column('project_folder_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_project_definitions_project_folder_id'), 'project_definitions', ['project_folder_id'], unique=True)
    op.create_foreign_key(None, 'project_definitions', 'file_nodes', ['project_folder_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_definitions', type_='foreignkey')
    op.drop_index(op.f('ix_project_definitions_project_folder_id'), table_name='project_definitions')
    op.drop_column('project_definitions', 'project_folder_id')
    # ### end Alembic commands ###
