"""add resource data table

Revision ID: 9c6aace0bc86
Revises: c1d41626f6c0
Create Date: 2026-09-11 18:40:48.375450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c6aace0bc86'
down_revision: Union[str, Sequence[str], None] = 'c1d41626f6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_resource_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['plugin_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugin_resource_records_resource_id'), 'plugin_resource_records', ['resource_id'], unique=False)
    op.create_index(op.f('ix_plugin_resource_records_user_id'), 'plugin_resource_records', ['user_id'], unique=False)
    op.create_table('plugin_resource_user_schemas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('schema_definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['plugin_resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'user_id', name='uq_plugin_resource_user_schema_resource_user')
    )
    op.create_index(op.f('ix_plugin_resource_user_schemas_resource_id'), 'plugin_resource_user_schemas', ['resource_id'], unique=False)
    op.create_index(op.f('ix_plugin_resource_user_schemas_user_id'), 'plugin_resource_user_schemas', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_resource_user_schemas_user_id'), table_name='plugin_resource_user_schemas')
    op.drop_index(op.f('ix_plugin_resource_user_schemas_resource_id'), table_name='plugin_resource_user_schemas')
    op.drop_table('plugin_resource_user_schemas')
    op.drop_index(op.f('ix_plugin_resource_records_user_id'), table_name='plugin_resource_records')
    op.drop_index(op.f('ix_plugin_resource_records_resource_id'), table_name='plugin_resource_records')
    op.drop_table('plugin_resource_records')
    # ### end Alembic commands ###
