"""add plugin table

Revision ID: b72040bfef6c
Revises: 824d96304556
Create Date: 2026-09-07 13:37:40.133480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72040bfef6c'
down_revision: Union[str, Sequence[str], None] = '824d96304556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('icon_url', sa.String(length=1000), nullable=True),
    sa.Column('banner_url', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('metadata_config', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'UNPUBLISHED', 'ARCHIVED', name='plugin_status'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unpublished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plugins_category'), 'plugins', ['category'], unique=False)
    op.create_index(op.f('ix_plugins_code'), 'plugins', ['code'], unique=True)
    op.create_index(op.f('ix_plugins_created_by'), 'plugins', ['created_by'], unique=False)
    op.create_index(op.f('ix_plugins_is_public'), 'plugins', ['is_public'], unique=False)
    op.create_index(op.f('ix_plugins_slug'), 'plugins', ['slug'], unique=True)
    op.create_index(op.f('ix_plugins_status'), 'plugins', ['status'], unique=False)
    op.create_table('plugin_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'DEPRECATED', name='plugin_version_status'), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('release_notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'version', name='uq_plugin_versions_plugin_version')
    )
    op.create_index(op.f('ix_plugin_versions_plugin_id'), 'plugin_versions', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_plugin_versions_status'), 'plugin_versions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_versions_status'), table_name='plugin_versions')
    op.drop_index(op.f('ix_plugin_versions_plugin_id'), table_name='plugin_versions')
    op.drop_table('plugin_versions')
    op.drop_index(op.f('ix_plugins_status'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_slug'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_is_public'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_created_by'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_code'), table_name='plugins')
    op.drop_index(op.f('ix_plugins_category'), table_name='plugins')
    op.drop_table('plugins')
    # ### end Alembic commands ###
