"""update plugin table

Revision ID: c1d41626f6c0
Revises: b72040bfef6c
Create Date: 2026-09-11 10:38:02.615061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1d41626f6c0'
down_revision: Union[str, Sequence[str], None] = 'b72040bfef6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scope', sa.Enum('GLOBAL', 'USER', name='plugin_resource_scope'), nullable=False),
    sa.Column('allow_user_schema_override', sa.Boolean(), nullable=False),
    sa.Column('schema_definition', sa.JSON(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'key', name='uq_plugin_resources_plugin_key')
    )
    op.create_index(op.f('ix_plugin_resources_plugin_id'), 'plugin_resources', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_plugin_resources_scope'), 'plugin_resources', ['scope'], unique=False)
    op.create_table('plugin_resource_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_type', sa.Enum('TEXT', 'LONG_TEXT', 'NUMBER', 'DECIMAL', 'BOOLEAN', 'DATE', 'DATETIME', 'EMAIL', 'PHONE', 'COUNTRY', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'URL', name='plugin_field_type'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('min_length', sa.Integer(), nullable=True),
    sa.Column('max_length', sa.Integer(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('pattern', sa.String(length=1000), nullable=True),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('default_value', sa.JSON(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['plugin_resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'key', name='uq_plugin_resource_fields_resource_key')
    )
    op.create_index(op.f('ix_plugin_resource_fields_resource_id'), 'plugin_resource_fields', ['resource_id'], unique=False)
    op.add_column('plugin_versions', sa.Column('definition_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_plugin_versions_definition_hash'), 'plugin_versions', ['definition_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_versions_definition_hash'), table_name='plugin_versions')
    op.drop_column('plugin_versions', 'definition_hash')
    op.drop_index(op.f('ix_plugin_resource_fields_resource_id'), table_name='plugin_resource_fields')
    op.drop_table('plugin_resource_fields')
    op.drop_index(op.f('ix_plugin_resources_scope'), table_name='plugin_resources')
    op.drop_index(op.f('ix_plugin_resources_plugin_id'), table_name='plugin_resources')
    op.drop_table('plugin_resources')
    # ### end Alembic commands ###
