"""add plugin project table

Revision ID: cfaa133fb040
Revises: 4ce2c8b906d1
Create Date: 2026-09-16 16:46:16.405557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfaa133fb040'
down_revision: Union[str, Sequence[str], None] = '4ce2c8b906d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_project_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_user_use', sa.Boolean(), nullable=False),
    sa.Column('allow_user_customization', sa.Boolean(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('resource_bindings', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plugin_id', 'key', name='uq_plugin_project_templates_plugin_key')
    )
    op.create_index(op.f('ix_plugin_project_templates_created_by'), 'plugin_project_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_plugin_project_templates_is_active'), 'plugin_project_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_plugin_project_templates_key'), 'plugin_project_templates', ['key'], unique=False)
    op.create_index(op.f('ix_plugin_project_templates_plugin_id'), 'plugin_project_templates', ['plugin_id'], unique=False)
    op.create_index(op.f('ix_plugin_project_templates_project_type'), 'plugin_project_templates', ['project_type'], unique=False)
    op.create_table('plugin_form_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_template_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('form_type', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('min_instances', sa.Integer(), nullable=False),
    sa.Column('max_instances', sa.Integer(), nullable=True),
    sa.Column('allow_user_use', sa.Boolean(), nullable=False),
    sa.Column('allow_user_customization', sa.Boolean(), nullable=False),
    sa.Column('global_config', sa.JSON(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('resource_bindings', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_template_id'], ['plugin_project_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_template_id', 'key', name='uq_plugin_form_templates_project_template_key')
    )
    op.create_index(op.f('ix_plugin_form_templates_created_by'), 'plugin_form_templates', ['created_by'], unique=False)
    op.create_index(op.f('ix_plugin_form_templates_is_active'), 'plugin_form_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_plugin_form_templates_key'), 'plugin_form_templates', ['key'], unique=False)
    op.create_index(op.f('ix_plugin_form_templates_project_template_id'), 'plugin_form_templates', ['project_template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugin_form_templates_project_template_id'), table_name='plugin_form_templates')
    op.drop_index(op.f('ix_plugin_form_templates_key'), table_name='plugin_form_templates')
    op.drop_index(op.f('ix_plugin_form_templates_is_active'), table_name='plugin_form_templates')
    op.drop_index(op.f('ix_plugin_form_templates_created_by'), table_name='plugin_form_templates')
    op.drop_table('plugin_form_templates')
    op.drop_index(op.f('ix_plugin_project_templates_project_type'), table_name='plugin_project_templates')
    op.drop_index(op.f('ix_plugin_project_templates_plugin_id'), table_name='plugin_project_templates')
    op.drop_index(op.f('ix_plugin_project_templates_key'), table_name='plugin_project_templates')
    op.drop_index(op.f('ix_plugin_project_templates_is_active'), table_name='plugin_project_templates')
    op.drop_index(op.f('ix_plugin_project_templates_created_by'), table_name='plugin_project_templates')
    op.drop_table('plugin_project_templates')
    # ### end Alembic commands ###
