"""update project question dependencies

Revision ID: d71901c30ddd
Revises: 253a3251d13d
Create Date: 2026-08-26 15:31:26.633001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71901c30ddd'
down_revision: Union[str, Sequence[str], None] = '253a3251d13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_question_dependencies', sa.Column('condition', sa.JSON(), nullable=False))
    op.add_column('project_question_dependencies', sa.Column('actions_if_true', sa.JSON(), nullable=False))
    op.add_column('project_question_dependencies', sa.Column('actions_if_false', sa.JSON(), nullable=False))
    op.drop_index(op.f('ix_project_question_dependencies_source_question_id'), table_name='project_question_dependencies')
    op.drop_constraint(op.f('uq_project_question_dependency_pair'), 'project_question_dependencies', type_='unique')
    op.drop_constraint(op.f('project_question_dependencies_source_question_id_fkey'), 'project_question_dependencies', type_='foreignkey')
    op.drop_column('project_question_dependencies', 'operator')
    op.drop_column('project_question_dependencies', 'value')
    op.drop_column('project_question_dependencies', 'source_question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_question_dependencies', sa.Column('source_question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project_question_dependencies', sa.Column('value', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('project_question_dependencies', sa.Column('operator', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('project_question_dependencies_source_question_id_fkey'), 'project_question_dependencies', 'project_questions', ['source_question_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_project_question_dependency_pair'), 'project_question_dependencies', ['target_question_id', 'source_question_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_project_question_dependencies_source_question_id'), 'project_question_dependencies', ['source_question_id'], unique=False)
    op.drop_column('project_question_dependencies', 'actions_if_false')
    op.drop_column('project_question_dependencies', 'actions_if_true')
    op.drop_column('project_question_dependencies', 'condition')
    # ### end Alembic commands ###
